config/routes.rb
Roroster::Application.routes.draw do
  resources :rosters

  root 'rosters#index'

  get '/rosters/:id/photo' => 'rosters#photo'

  

end

app/models/roster.rb
class Roster
  include MongoMapper::Document

  key :name, String
  key :overall, Integer
  key :scheduling, Integer
  key :fun, Integer
  key :day, String
  key :night, String
  key :food, String
  key :contact1, String
  key :contact2, String
  key :contact3, String
  key :freq, Integer
  key :deadline, Time

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  before_action :set_roster, only: [:show, :edit, :update, :destroy]

  # GET /rosters
  # GET /rosters.json
  def index
    @rosters = Roster.all
  end

  def remainingT
    @rosters.each do |roster|
      @remainingTime = (roster.deadline - Time.new)/1.day
      puts remaind
    end
  end

  # GET /rosters/1
  # GET /rosters/1.json
  def show
  end

  # GET /rosters/new
  def new
    @roster = Roster.new
  end

  # GET /rosters/1/edit
  def edit
  end

  # POST /rosters
  # POST /rosters.json
  def create
    @roster = Roster.new(roster_params)
    @roster.deadline =  Time.new + (@roster.freq.days)

    respond_to do |format|
      if @roster.save
        format.html { redirect_to @roster, notice: 'Roster was successfully created.' }
        format.json { render action: 'show', status: :created, location: @roster }
      else
        format.html { render action: 'new' }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1
  # PATCH/PUT /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update_attributes(roster_params)
        format.html { redirect_to @roster, notice: 'Roster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.json
  def destroy
    @roster.destroy
    respond_to do |format|
      format.html { redirect_to rosters_url }
      format.json { head :no_content }
    end
  end

  def photo
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roster
      @roster = Roster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roster_params
      params.require(:roster).permit(:name, :overall, :scheduling, :fun, :day, :night, :food, :contact1, :contact2, :contact3, :freq, :deadline)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roroster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="countdown.js"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rosters/_banner.html.erb
<div class="page-header topbar text-center">
  <h1>RoRoster <small>giving you full-court advantage</small></h1>
</div>
<div>

app/views/rosters/_form.html.erb
<%= form_for(@roster) do |f| %>
  <% if @roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
      <% @roster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="statBox span6 offset3">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :overall %><br>
      <%= f.text_field :overall %>
    </div>
    <div class="field">
      <%= f.label :scheduling %><br>
      <%= f.text_field :scheduling %>
    </div>
    <div class="field">
      <%= f.label :fun %><br>
      <%= f.text_field :fun %>
    </div>
    <div class="field">
      <%= f.label :day %><br>
      <%= f.text_field :day %>
    </div>
    <div class="field">
      <%= f.label :night %><br>
      <%= f.text_field :night %>
    </div>
    <div class="field">
      <%= f.label :food %><br>
      <%= f.text_field :food %>
    </div>
    <div class="field">
      <%= f.label :contact1 %><br>
      <%= f.text_field :contact1 %>
    </div>
    <div class="field">
      <%= f.label :contact2 %><br>
      <%= f.text_field :contact2 %>
    </div>
    <div class="field">
      <%= f.label :contact3 %><br>
      <%= f.text_field :contact3 %>
    </div>
    <div class="field">
      <%= f.label :freq %><br>
      <%= f.text_field :freq %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
    
  </div>
<% end %>

app/views/rosters/_playerStats.html.erb
<% @rosters.each do |roster| %>
      <div class= "span4"> 
            <div class="clocks"> <script> var myCountdown1 = new Countdown({time:<% @remainingTime %>}); </script> </div>
            <div class= "nameBox"><%= roster.name %></div>
            <div class= "statBox">      
                  <div><span class="choices"><%= link_to 'Edit', edit_roster_path(roster) %></span>
                        <span class= "choices"><%= link_to 'Destroy', roster, method: :delete, data: { confirm: 'Are you sure?' } %></span>
                  </div>
                  <div> Overall Meter: <%= roster.overall %></div>
                  <div> Scheduling Ease: <%= roster.scheduling %></div>
                  <div> Fun Meter: <%= roster.fun %></div>
                  <div> Avail Daytime: <%= roster.day %></div>
                  <div> Avail Nighttime: <%= roster.night %></div>
                  <div> Food Pref: <%= roster.food %></div>
                  <div> Contact Method 1: <%= roster.contact1 %></div>
                  <div> Contact Method 2: <%= roster.contact2 %></div>
                  <div> Contact Method 3: <%= roster.contact3 %></div>
                  <div> Contact Freq Desired: <%= roster.freq %></div>
            </div>
      </div>
<% end %>

app/views/rosters/_showChanges.html.erb
<div class= "nameBox span6 offset3">Updated Player Stats</div>
<div class= "statBox span6 offset3">
  <p id="notice"><%= notice %></p>
  <div>
    <strong>Name:</strong>
    <%= @roster.name %>
  </div>

  <div>
    <strong>Overall:</strong>
    <%= @roster.overall %>
  </div>

  <div>
    <strong>Scheduling:</strong>
    <%= @roster.scheduling %>
  </div>

  <div>
    <strong>Fun:</strong>
    <%= @roster.fun %>
  </div>

  <div>
    <strong>Day:</strong>
    <%= @roster.day %>
  </div>

  <div>
    <strong>Night:</strong>
    <%= @roster.night %>
  </div>

  <div>
    <strong>Food:</strong>
    <%= @roster.food %>
  </div>

  <div>
    <strong>Contact1:</strong>
    <%= @roster.contact1 %>
  </div>

  <div>
    <strong>Contact2:</strong>
    <%= @roster.contact2 %>
  </div>

  <div>
    <strong>Contact3:</strong>
    <%= @roster.contact3 %>
  </div>

  <div>
    <strong>Freq:</strong>
    <%= @roster.freq %>
  </div>
</div>

app/views/rosters/edit.html.erb
<div> <%= render 'banner'%> </div>

<div class="span1 offset10"><%= link_to 'Back', rosters_path %></div>

<div class="nameBox span6 offset3"> <h2>Edit Player Stats</h2> </div>
<div> <%= render 'form' %> </div>

<div> <%= link_to 'Show', @roster %> </div>
<div><%= link_to 'Back', rosters_path %> </div>

app/views/rosters/index.html.erb
<%= render 'banner'%>
<button class="btn"><%= link_to 'New Recruit', new_roster_path %></button
	> 
</div>
<div class="playStats">
  <%= render 'playerStats'%>
</div>

app/views/rosters/new.html.erb
<div> <%= render 'banner'%> </div>

<div class="span1 offset10"><%= link_to 'Back', rosters_path %></div>

<div class="nameBox span6 offset3"><b> Add New Player </b></div>

<div><%= render 'form' %></div>

app/views/rosters/photo.html.erb
<%= render 'banner'%>

<h2>Update Player Photo</h2>

app/views/rosters/show.html.erb
<%= render 'banner'%>

<div class="span2 offset10"><%= link_to 'Edit', edit_roster_path(@roster) %> |
<%= link_to 'Home', rosters_path %></div>

<%= render 'showChanges'%>